### ISSUE TITLE
Could not find the required component 'opt_msgs' after cd publisher && catkin_make

### ISSUE THREAD

**Issue by thiteixeira** [OpenPTrack/ndn-opt#2]
Hi,
I am trying to install and run the ndn-opt on a Ubuntu 14.04 machine. I followed the ROS installation instructions from https://github.com/OpenPTrack/open_ptrack/wiki/Installation-Guide and then the ndn-opt installation from https://github.com/OpenPTrack/ndn-opt/tree/master/publisher

I am getting the following error message after I run `cd publisher && catkin_make`
```
CMake Warning at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by "opt_msgs" with any
  of the following names:

    opt_msgsConfig.cmake
    opt_msgs-config.cmake

  Add the installation prefix of "opt_msgs" to CMAKE_PREFIX_PATH or set
  "opt_msgs_DIR" to a directory containing one of the above files.  If
  "opt_msgs" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  ros2ndn_converter/CMakeLists.txt:12 (find_package)


-- Could not find the required component 'opt_msgs'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "opt_msgs" with any
  of the following names:

    opt_msgsConfig.cmake
    opt_msgs-config.cmake

  Add the installation prefix of "opt_msgs" to CMAKE_PREFIX_PATH or set
  "opt_msgs_DIR" to a directory containing one of the above files.  If
  "opt_msgs" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  ros2ndn_converter/CMakeLists.txt:12 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/nslab3/ndn-opt/publisher/build/CMakeFiles/CMakeOutput.log".
See also "/home/nslab3/ndn-opt/publisher/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed
```

The `opt_msgsConfig.cmake` is in the `../workspace/ros/catkin/devel/share/opt_msgs/cmake` folder. How do I update the `opt_msgs_DIR`? Is this the solution to this issue?

Thank you

**Comment by jburkeucla** [comment]
Is there a specific reason you are trying to install ndn-opt?  It is not needed for normal operation
J

**Comment by thiteixeira** [comment]
Hi Jeff,
I would like to use the NDN Pub/Sub nodes for OpenPTrack.

**Comment by thiteixeira** [comment]
Hi,
It worked after I did the following:

It is suggested that the `/open_ptrack` folder contained in your `/home` folder be deleted, and that a symlink be placed in the `/home` folder from the `/workspace` folder. E.g.: `ln -s ~/workspace/ros/catkin/src/open_ptrack ~/open_ptrack`

**Comment by nanodust** [comment]
excellent, glad you got it ! let us know how your project works out !!
